name: Print File Contents

on: [push]

jobs:
  print-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display contents of message.txt
        run: New_File
